apiVersion: v1
kind: Pod
metadata:
  name: nginx-minimal
spec:
  initContainers:
    - name: config-setup
      image: busybox:1.36
      command: ['sh', '-c']
      args:
        - |
          mkdir -p /shared/config
          echo "worker_processes auto;" > /shared/config/nginx-custom.conf
          echo "Setup completed"
      volumeMounts:
        - name: shared-config
          mountPath: /shared
  containers:
    - name: nginx
      image: nginx:1.26.0
      ports:
        - containerPort: 80
      volumeMounts:
        - name: shared-config
          mountPath: /etc/nginx/conf.d
          readOnly: true
    - name: nginx-exporter
      image: nginx/nginx-prometheus-exporter:1.1.0
      ports:
        - containerPort: 9113
      args:
        - -nginx.scrape-uri=http://localhost/nginx_status
      env:
        - name: CONST_LABELS
          value: "environment=production"
  volumes:
    - name: shared-config
      emptyDir: {}